const { buildTemplate, checkAgainstTemplate } = require('./template');

describe('buildTemplate', () => {
  it('produces sorted keys with empty values', () => {
    const maps = [{ B: '2', A: '1' }, { C: '3' }];
    const result = buildTemplate(maps, { includeComments: false });
    expect(result).toBe('A=\nB=\nC=\n');
  });

  it('uses placeholder when provided', () => {
    const maps = [{ FOO: 'bar' }];
    const result = buildTemplate(maps, { includeComments: false, placeholder: 'CHANGE_ME' });
    expect(result).toBe('FOO=CHANGE_ME\n');
  });

  it('includes comment header by default', () => {
    const maps = [{ X: '1' }];
    const result = buildTemplate(maps);
    expect(result).toContain('# Generated by envdiff template');
    expect(result).toContain('X=');
  });

  it('deduplicates keys across maps', () => {
    const maps = [{ KEY: 'a' }, { KEY: 'b', OTHER: 'c' }];
    const result = buildTemplate(maps, { includeComments: false });
    const lines = result.trim().split('\n');
    expect(lines).toHaveLength(2);
    expect(lines[0]).toBe('KEY=');
    expect(lines[1]).toBe('OTHER=');
  });
});

describe('checkAgainstTemplate', () => {
  it('detects missing keys', () => {
    const template = { A: '', B: '', C: '' };
    const env = { A: '1' };
    const { missing, extra } = checkAgainstTemplate(template, env);
    expect(missing).toEqual(expect.arrayContaining(['B', 'C']));
    expect(extra).toHaveLength(0);
  });

  it('detects extra keys', () => {
    const template = { A: '' };
    const env = { A: '1', Z: '9' };
    const { missing, extra } = checkAgainstTemplate(template, env);
    expect(missing).toHaveLength(0);
    expect(extra).toContain('Z');
  });

  it('returns empty arrays when maps match', () => {
    const template = { A: '', B: '' };
    const env = { A: '1', B: '2' };
    const { missing, extra } = checkAgainstTemplate(template, env);
    expect(missing).toHaveLength(0);
    expect(extra).toHaveLength(0);
  });
});
