const fs = require('fs');

/**
 * Generate a .env template from one or more parsed env maps.
 * Keys are included, values are replaced with empty or placeholder.
 */
function buildTemplate(envMaps, opts = {}) {
  const { placeholder = '', includeComments = true } = opts;
  const allKeys = new Set();
  for (const map of envMaps) {
    for (const key of Object.keys(map)) {
      allKeys.add(key);
    }
  }
  const lines = [];
  if (includeComments) {
    lines.push('# Generated by envdiff template');
    lines.push(`# Created: ${new Date().toISOString()}`);
    lines.push('');
  }
  for (const key of [...allKeys].sort()) {
    lines.push(`${key}=${placeholder}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Write template content to a file path.
 */
function writeTemplate(outputPath, content) {
  fs.writeFileSync(outputPath, content, 'utf8');
}

/**
 * Check which keys from a template are missing in a given env map.
 */
function checkAgainstTemplate(templateMap, envMap) {
  const missing = [];
  const extra = [];
  for (const key of Object.keys(templateMap)) {
    if (!(key in envMap)) missing.push(key);
  }
  for (const key of Object.keys(envMap)) {
    if (!(key in templateMap)) extra.push(key);
  }
  return { missing, extra };
}

module.exports = { buildTemplate, writeTemplate, checkAgainstTemplate };
